### ISSUE TITLE
name 'n' is not defined

### ISSUE THREAD

**Issue by todeveloper21** [ziyeshanwai/python-deformation-transfer#2]
name 'n' is not defined when run demo.

**Comment by ziyeshanwai** [comment]
can you provide more detail about the error "name 'n' is not defined when run demo" @zhenzhen823

**Comment by todeveloper21** [comment]
line 181 in the main.py
sigma2 = (1.0 / n) * np.multiply(cent_0, cent_0).sum()
n is not defined.

**Comment by ziyeshanwai** [comment]
@zhenzhen823  the error is fixed, n = Points_A.shape[1]

**Comment by todeveloper21** [comment]
Thank you.
