### ISSUE TITLE
Ask for suggestions about deformation transfer

### ISSUE THREAD

**Issue by veloseptimus** [ziyeshanwai/python-deformation-transfer#5]
Sorry to bother, this is a code learner. I'm trying to transfer expression from landmarks to a face mesh template in a realtime method. I found the paper of Sumner but the methed is too slow. Is there any other solutions? Do you have any suggestions?

**Comment by ziyeshanwai** [comment]
you can try the matlab version https://github.com/SuwoongHeo/Deformation-Transfer-Matlab , it is more fast , about 1 min
